name: Contributor Updater

on:
  push:
    paths:
    - src/asciidoc-pages/**
    branches:         
    - main

jobs:
  check_contributors:
    name: Check Contributors
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - id: files
      uses: jitterbit/get-changed-files@v1
      
    - run: pip3 install bs4

    - run: |
        # shellcheck disable=2043
        for changed_file in ${{ steps.files.outputs.all }}; do
          if [[ ${changed_file} =~ ^src/asciidoc.*.adoc ]]; then
            current_authors=$(grep ':page-authors:' "${changed_file}" | sed -n -e 's/^.*page-authors: //p')
            contibutors=$(python3 .github/workflows/github-file-contributors.py --file "${changed_file}")
            for contibutor in ${contibutors}; do
              if ! echo "${current_authors}" | grep "${contibutor}"; then
                echo "adding ${contibutor}"
                current_authors_replacement="${current_authors}, ${contibutor}"
                echo "${current_authors_replacement}"
                sed -i "s/${current_authors}/${current_authors_replacement}/g" "${changed_file}"
              fi
            done
          fi
        done

    - uses: gr2m/create-or-update-pull-request-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ADOPTIUM_TEMURIN_BOT_TOKEN }}
      with:
        title: "Update Asciidoc Contributors"
        path: "src/asciidoc-pages/"
        commit-message: "contributors: update asciidoc contributors"
        author: "eclipse-temurin-bot <temurin-bot@eclipse.org>"
